server:
  port: 2100

spring:
  application:
    name: spring-cloud-eureka-consumer-01     # 指定发布的微服务名（以后调用时，只需该名称即可访问该服务）

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    healthcheck:
      enabled: true  # 开启健康检查（依赖spring-boot-starter-actuator）

feign:
  hystrix:
    enabled: true # 启用熔断的开关

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 解决Feign/Ribbon第一次请求失败的问题
            timeoutInMilliseconds: 5000
