server:
  port: 4100

spring:
  application:
    name: sping-cloud-eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fillavacancy/spring-cloud-examples  # 配置git仓库的地址
          searchPaths: config-prod                             # git仓库下的相对地址（多个则用半角逗号分隔）
          # username: username                                 # 只有private的项目才需配置用户名和密码
          # password: password                                 # 只有private的项目才需配置用户名和密码

management:
  security:
    enabled: false # 刷新时，关闭安全验证

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true  # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
      defaultZone: http://192.168.10.118:1100/eureka/